site_name: MkDocs RTD Template
site_description: 示例文档项目，用于 Read the Docs 自动构建
site_author: changzhiming
site_url: https://yourproject.readthedocs.io

docs_dir: docs
site_dir: site

# theme:
#   name: readthedocs
#   highlightjs: true
#   hljs_languages:
#     - python
#     - cpp
#     - yaml

# Theme
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.annotate
    - content.code.copy

nav:
  - 首页: index.md
  - 使用指南: guide.md
  - API:
      - 使用示例: api/usage.md


# Extensions - 添加 Mermaid 支持
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html


plugins:
  - search

repo_url: https://github.com/yourname/mkdocs-rtd-template
repo_name: GitHub
edit_uri: edit/main/docs/
